
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 1127246797971132537
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
    
	#Image Keys
	[[custom.variables]]
        name = "largeImageKey"
        value = "https://i.imgur.com/HqWmPnT.gif"
    [[custom.variables]]
        name = "smallImageKey"
        value = "https://i.imgur.com/alFUtQ5.png"
	
	#Image Text:
    [[custom.variables]]
        name = "largeImageText"
        value = "Insomnia: Hardcore - Minecraft %mcver%"
	[[custom.variables]]
        name = "smallImageText"
        value = "Crism Modpacks"
	
	#Button label:
	[[custom.variables]]
        name = "CF_Button_Label"
        value = "Download 'Insomnia: Hardcore'"

	#Button url:
	[[custom.variables]]
        name = "CF_Button_URL"
        value = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore/install"

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "'Insomnia: Hardcore' is loading"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[init.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Currently chilling"
	#The seconds line of text under the app name
	state = "Main Menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[main_menu.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Looking for a server"
	#The second line of text under the app name
	state = "Multiplayer Menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[server_list.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "Looking for a Realm"
	#The second line of text under the app name
	state = "Realms Menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[realms_list.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Joining a game"
	#The second line of text under the app name
	state = "Loading..."
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[join_game.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "In %world%"
	#The second line of text under the app name
	state = "Playing Singleplayer"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[single_player.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "In %world%"
	#The second line of text under the app name
	state = "Playing on '%servername%' with %players% players"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[multi_player.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[realms.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Minecraft"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = ["%largeImageKey%"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "%largeImageText%"
	#The Asset ID of the image to display as the small image
	smallImageKey = ["%smallImageKey%"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "%smallImageText%"

	#The buttons to display on Discord
	[[generic.buttons]]
		label = "%CF_Button_Label%"
		url = "%CF_Button_URL%"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = "In the Overworld"
		state = ""
		largeImageKey = [""]
		largeImageText = ""
		smallImageKey = [""]
		smallImageText = ""
		buttons = []

#	[[dimension_overrides.dimensions]]
#		name = "the_nether"
#		description = "In the Nether"
#		state = ""
#		largeImageKey = [""]
#		largeImageText = ""
#		smallImageKey = ["mclogo"]
#		smallImageText = "%smallImageText%"
#		buttons = []

#	[[dimension_overrides.dimensions]]
#		name = "the_end"
#		description = "In the End"
#		state = ""
#		largeImageKey = [""]
#		largeImageText = ""
#		smallImageKey = [""]
#		smallImageText = ""
#		buttons = []

