name = "InsomniaHardcore"
author = "CrismPack"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fad3ee41a4eb6c2682fd1c6b52e9029a882ccc48a2706e477791c5cdbec94d33"

[versions]
fabric = "0.14.11"
minecraft = "1.18.2"
