name = "InsomniaHardcore"
author = "CrismPack"
version = "1.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ef10832ca6a9abf1620d0b50f6e24378651ad5bbe6c9f5c7ac961469258b862"

[versions]
fabric = "0.14.11"
minecraft = "1.18.2"
