name = "InsomniaHardcore"
author = "CrismPack"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d15046bd6555fd64a055522ae6b1da2c3c6b0cd8ca6c86aa493352903c724ba0"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
