modpack_name: "InsomniaHardcore"
minecraft_version: "1.20.1"

export_client: True
export_server: False

refresh_only: False
update_bcc_version: True
cleanup_temp: True
create_release_notes: True
server_mods_remove_list: ["From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar"]
print_path_debug: True
update_publish_workflow: True

bh_banner: "https://raw.githubusercontent.com/CrismPack/CDN/refs/heads/main/desc/insomnia/bhbanner.png"