version = 3

[clientSideConfig]

	[clientSideConfig.modifyMaxVDConfig]
		enableExtRenderDistanceProtocol = false
		enabled = false

[noTickViewDistance]
	maxConcurrentChunkLoads = 2
	enableExtRenderDistanceProtocol = false
	maxViewDistance = 32
	
[ioSystem]
	gcFreeChunkSerializer = false

[threadedWorldGen]
	enabled = true