# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = ["Failed to load model delightfulcreators:", "Failed to modify baked model after bake", "Too many items! Cleared 1001 tasks.", "Invalid mod icon for icon source", "Mod icon must be a square for icon source"]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Failed to load model delightfulcreators:", "Failed to modify baked model after bake", "Too many items! Cleared 1001 tasks.", "Invalid mod icon for icon source", "Mod icon must be a square for icon source"]