name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "530791ee4a9ecbbe1e488193264ead6b7b76c306902268df413cf5958344cf63"

[versions]
fabric = "0.15.3"
minecraft = "1.18.2"
