name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e496b108c6bf0d4b75f987086e0ce96f1f96a797fd27748eeaca314cd949a415"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
