name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4b3b1a535fa4afb80a259668ca92e233e8ab6dbd835be22f8749a17512a6ace"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
