name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2198d0891f620feca2076c316ca581f031dbd759a0120de9f17cb7f02589ff26"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
