name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "387a482f461677c62f1d92776325e7bca68f04360bd19972ab79b7a0af8fe6dc"

[versions]
minecraft = "1.20.1"
quilt = "0.20.1"
