name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d7f635ddb6056175d788eaa488633fd2a0f8a067744a5f0c50d7dce33921666"

[versions]
fabric = "0.14.23"
minecraft = "1.18.2"
