name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71954f6024cddcfeda27b39aa9df02ed667850b64475bb44728135de69cbe251"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
