name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ad68e35fa1988516cadff295f4c48da6e57c1b33fd4f33426c480ff73f5cc46"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
