name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d7e2709b4be5058e93e0e3dee6b016b155ad5cce15cfd1cb5e111455ce67a99"

[versions]
fabric = "0.14.25"
minecraft = "1.18.2"
