name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a03de57fc008e2123f99333319561091eeb55ec2b2b1716aa3501b2149cdea6"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
