name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "720f46981f68e0d4eeba6b4a526901fe967000a8ae844b55a0c19699466d450d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
