name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8aa8381a61d02c4786165f714a9eb14ca1cd745e8b9514759fe8ac07be90799"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
