name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b465274aa75d64fb27ab0e911118d672afea7c90a9c2f3a70686723713e16345"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
