name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.3a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65743956398c15fa4ef069f084ed159bb05ae53cfbf5e5fcb6624831edf919c4"

[versions]
fabric = "0.14.25"
minecraft = "1.18.2"
