name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d339d6508040531b19b62122aab19718ffcb8e5f06e8a06254dd9cc61d91fcd"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
