name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2fddf25ecb368245133adf78a829fde47f9de0f103b537fa8b90e8df022a0d1"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
