name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8391800626814173e6b47673ef6d5943fca2a44d66e64a8804444a82c3d8d2c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
