name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e524100ec933fc10f7adbea03035151f6753a39bff4c9280ded1fe78d136750"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
