name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5941fda8c49bfdd65ae2251acd607f41ba53a78465c6d87134eba39a72a2a008"

[versions]
fabric = "0.14.24"
minecraft = "1.18.2"
