name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5965b27116bef0b227febfa7c4ece28734f98734091a9387e7bb985f678d562"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
