name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2fcbb51ae19d51993878f7f0c7f17f236a8e2fcbd7a04f67da03fbf9a31b6e3"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
