name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca416550dac277aecb958678d28675311e3e725df63c7e24532b4891b8d4dcf7"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
