name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24219a5e36801147134956fd4063ecf83ec4030239f8091944c7983b738fe477"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
