name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16691fd63acbce52fde30ca9ac4300ad37b04c750cae38c1f21d3d81fd70f343"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
