name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0344dcac9ba886fd91e1fd70a4b570e6c901d590b723a9dce64ddc89fadd53b"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
