name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac341a91cdd7e981ee0e5b40cd18c5d0d7f0b23bfd1305432fb5299438b6ae01"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
