name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f32a548cb1f2b81674438779f07ebcfb0a5adfa4073a9cbf1078c3f4fe60430"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
