name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "106d11e5221fd199525122238c493ca2ae3f0fc1c921bae6605539610f6a38ee"

[versions]
fabric = "0.14.23"
minecraft = "1.18.2"
