name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dd633c985efa50cf7e07abb658f963460132bef2484ce272fbd2faf32853b31"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
