name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a61a0d95c693580037b43168f62d205de029fd0f3af207718172b6d92b76f319"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
