name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a61e45e3a548abe8d5d42c58daf06b3c3a980605a93914a1f3eb7dacafc42b3b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
