name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8282ca28c46dd5ccd206ce36d8a6d8927430a8aac47047c66b70f9ad0d5955be"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
