name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "104f514a9ad773276b36e2dad761d14f08fe376b2a27028c821b2a042994cb80"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
