name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0371dbe7ce1a74d2fdd3a919d2cdbaccb7649c12351c180ea2d37ed8779c8402"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
