name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b46dbd7e0d8d97616b90e8a29e107fd84489a2d29571fddad41650c59b92e312"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
