name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27c29f849ff1a7a31bf11462601fac37ed8265b12ad7748107b13eeb1c48cb3c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
