name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "719aecca7bd4f275052722ab5ed5a95fd2bf4277b8b031fdfa87ad5694fa8909"

[versions]
fabric = "0.15.3"
minecraft = "1.18.2"
