name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a500eaef137e5676b8afbbb3ccd30e059db26a376ad7bed5c1efd01bac82b58c"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
