name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8a6f47148211b9975f518d3bf518b6f6767883f3fdb0648f7284cf2d08b3ab7"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
