name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c94e600aca4c24307211f27cbd5290facf96c919de982661ea84e4cae8f9dab5"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
