name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23457cc1aa3a6b2b9c220e071817d158c5bc5eec6c3ef4720e9e19e271cd699a"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
