name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c96c7bb58e25b4370fba76fc8b3a0589261d33087d050c1396c7ddb6894eebf6"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
