name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "098db5b76fa5ea10abddef9654f4440256b0e2e7fce5773c7cb5cb6f277a01d7"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
