name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c933e9e69ccdeedb272ea36240ce17ab3194a1d86393839636d06e1707067df3"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
