name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c06b0fdbe805831a876d7fd449eaf722f6efc3489355b0f98b462799650d955f"

[versions]
fabric = "0.14.23"
minecraft = "1.18.2"
