name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "763102c9a5e81a63cd724af8a050a4258f739aa96853be4c5625f9c6021c7d3a"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
