name = "InsomniaHardcore"
author = "CrismPack"
version = "2.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc94815f1c432771da106d6d64271a5270621b9da6dcaf5737360e2b1440b000"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
