name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00d4bd8b75df3b61f624a2b7508e74770dac6f5b204e63c8a9a9bc1580aaa07f"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
