name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "509f2ae3b0e5e484a5c3d1c1040ffea73ce77a5f4f3d54135ac530b9539a70f4"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
