name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c38f6ba5e761dfb06e41f2bfebb57dddc64cd1d800ecfb0e8020ec3beedbab73"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
