name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "973d10fa45cd9d8b6fb131c9433a9f87850aeadda2dc390d1f3ef5213f003cb9"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
