name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8749c04a55f725d17f98d5b5b9a3bf314cb536722ed7c91f6376eb1fdfd0fd4f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
