name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d21285db33838780e2155e746353fae79b918ee3dcde8eabadfdaab78f4a443"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
