name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c0d887bc07db0c1a5fa6de4f4bc6504e022d2164bf85dedf66293b211d80aaa"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
