name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd489680063748229d150b2c8856a7595ac747b47c07db2408721fc5102df9f0"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
