name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7037141d2fec03c6f01d060e254d7eef4a25585c34f3fc95be8988c6eef1b3ba"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
