name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "934682a00eefb7aa170a6c01db7ef30526b9ee6df06d0f98e4d84d78ce629214"

[versions]
fabric = "0.14.25"
minecraft = "1.18.2"
