name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7c58cac66476f3991db1d952b4ba57720c914215798d059db748826aaeeb3b0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
