name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "551854a9b095e3783f94c6954af96060f593d500624a1d911766f4fce7081799"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
