name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a74a06512dfa96065c9063572ae4a540b842308d4e13ab984fc889260e740c0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
