name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f77445a1632297bf4bf26b3b13d3e7062f24d31301ed5c257643081ab20afc60"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
