name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57d7b0c08dee2c9035a1885c41402e48dc46dc58ac1c521f15bfbd0f15e43745"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
