name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "899f346e99848cc8c4e285eecbaaae31ca1a492e9d4fea63a24846301ec71041"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
