name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3bfd014ba29a05367ef73a3e5ca6afd4a19374717370e3de0044f45aed809d7"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
