name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b46efbe7f324a106b3213d693064443b626b4a2cf85fc687662a674f467c6d90"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
