name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "126ddd8ffe2cb0a8471a517b83c2c4f2bdd67c1753dff3a4e2ff42ad923df65d"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
