name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e660101285f7ebc5e0dce8d67bb97c9d20f7571d23ee007334e11bd51968296"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
