name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df1214eadfa5f923c38002975fdf62c30e827172d780e7e1219870e6489db21d"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
