name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f57f72749a65e3d945fc9f099242c327ce43049ee2ba3b2706a593889f235b4c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
