name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1660d4379f3d1af564c5ae57df84c0b9751f030b2653861ad837499eabef8915"

[versions]
fabric = "0.14.23"
minecraft = "1.18.2"
