name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0518d7024c33d458ed459eac50344b2706997625e33e3d17412b95c351d3288"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
