name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef65c19e51c00b3f0ada2a74b75496da01f997f2ce8e1870da65236b777f134d"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
