name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8cf51f2edc522d2333f5218bf6f94e4fbb2fd146638d1b253043f4f91b38fce"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
