name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac5ffc2a374c227d37d115dff5081f987c0ab9f9f4d423ce03b08186974390bb"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
