name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "521294e67561959dd53b5a5c32c335b2a3c7289410f2b359b0a81784c5028bd4"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
