name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e86e3d48ee49f17ee1e8d8ced3dc7ffd918dd77fb60416208d6ef1fdbc5bfdce"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
