name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccb71d5fe7cf981b908e0dbfdccbb0a46bfc26facde54c1a62611dbf67b56155"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
