name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66906a1396922d69786ae907f8de32943841ee906104f00e0debb13093fd4b4d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
