name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1402d4a71a35d2185f71c51539c5d80d9b6a86231fd81dd74ef8a475b054097a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
