name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc6b8fec41cfb38ce0c8200c42deb9883f06d6879bc197de8368443570def30"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
