name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8406961f47579ebd9a2b62441c00863ff3987c2f5131e68e7274a14510fab836"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
