name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "565a0e00b46e7d6697666bdf3c8d42668255d120f5a3bd35a48dbcdaecc7c99a"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
