name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b746e72482da8a4a4957edcd35c39e9f30b7e53fed7d98f0c2171fafd2b3a422"

[versions]
fabric = "0.14.21"
minecraft = "1.18.2"
