name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5298bbd7ecdef07fc3d12138a8cb8d2ccc5df4ef1b05da196ec8028bf2284e7"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
