name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b55e8613cda6ccbcdc6179f04fe4a20612d91cbeebf4a4481515aa2a5387d108"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
