name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "884e523cb9856883f17d3763548c044929ccab6952a2e62cd57dfb3bda43aedc"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
