name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c5689049c4c86cd7adf5bff28e5d99f255dbc8da1ae83d0d9f0eee9d37956e6"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
