name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "681ff852c70c2b207e6960049e586ddded9a282bccd7fe985e825c7140414cc0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
