name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db03b08b4aff0ba20154506a11c742b5aef1606fcab363eee002894794d46201"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
