name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08a247d5894d9c148dd08a7eda332345bbc710c5544ac431e473d14f9452fc75"

[versions]
fabric = "0.15.3"
minecraft = "1.18.2"
