name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f40ce26e753cedb288e7e6d6c1becc5bd0847805258526ef0de531ee7b59040c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
