name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9785a579c474c792f96239cc8cc91c3d9043dc162bd18e2394b7e51c977da0ee"

[versions]
fabric = "0.14.18"
minecraft = "1.18.2"
