name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0698b0a3e42a2e35663cb3fdee06ed0aae65db49b0ab1980cddd5451a896273c"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
