name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ff419fd2f292a8905408eaf911ffa5953d0541a7728b0ef0d10c14ca22c8144"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
