name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b56297c7a03ac55714adf158f6911bedbd29c50231c5ac71da8f9621426caadd"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
