name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "517bb33fd9a42b44ea7281d7bb7f3c88932af2937a1b12452ad46bfe727704e7"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
