name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4572e2ac49488a87aa99d5f9632622916ee46894b55560ae0476cadfbd30fa2"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
