name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59c2433f2ac54cb3fac8ad4af664127df6a6b63a9bae2156640c99d85423f480"

[versions]
fabric = "0.14.18"
minecraft = "1.18.2"
