name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9a12cbe9fc41a6ea9f601f66174fb901404ccaa46552c7f6df591c7741a87a6"

[versions]
fabric = "0.15.3"
minecraft = "1.18.2"
