name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "319d493664e42986ce76c990e7035e1e574b1be4ac44c61c6519ef82a9a2f070"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
