name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c70a20b46743f3a1f6447c9bd7ded19958c85df375dfadbecc3b4a1e0d1f4305"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
