name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ae2fcb9a19805db78b42097b9a9ffdb9a060ecd13a66c1f84b02ddef5bb7365"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
