name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d839bcb3b1a0c732a2b69b58ecc369efc5bc019ba043297b4b1c3269f3be653"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
