name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aac457402cca8adda941bd603c1f07d022b90636935d53c108fdb5f4fe2cf1bf"

[versions]
fabric = "0.14.18"
minecraft = "1.18.2"
