name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d79a81d2a6e2f17a1d17ffa5f0025008317a102a8888d0046eec8f3b96fc40b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
