name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fc41e5a2871306ec9854e805b5172dcbbdc632ca1c6ae18ca78b5217dd2181a"

[versions]
fabric = "0.14.24"
minecraft = "1.18.2"
