name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acf6c273cb4029613321a9ef7c8611ae01bbceb0abf2301c195eaebf8d3dd517"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
