name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4478668cbf9ee94c4642da18308d40212b3a16024ca671138527ecbbff98e97"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
