name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02ebd41a6b5285f28c25392437a924f07581059bf3a939facabb3aa632764017"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
