name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86d514898332462f7cd813af47907dc0e7fac4219fb5afb9e45b29280868e0b3"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
