name = "InsomniaHardcore"
author = "CrismPack"
version = "2.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6f8a9d69365f2356b29c172e2d3ad7e24975ae973fff41e2937f89a396918c4"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
