name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f294aec4fb36b9f6ad2c0479ed75a17399a608be1b6b1cb5d5738701f8dd422"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
