name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "111c413e1576394da9b769476940a9cb348ba1c5400f55d5d2c873edc78a0f90"

[versions]
fabric = "0.14.24"
minecraft = "1.18.2"
