name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35c128535ae5c8b8ced75f5339db8b5937228af3f795ffeca986701f6b202089"

[versions]
fabric = "0.14.17"
minecraft = "1.18.2"
