name = "InsomniaHardcore"
author = "CrismPack"
version = "2.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "788a705c0139362740b55ad7e929586ed059fca0f111e87db58d9ed6f73783d7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
