name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fee28a41d5070e835637e260733cf3e9be89afe8804e99564ca06022d2a792d"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
