name = "InsomniaHardcore"
author = "CrismPack"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97a932039da203475a8e1a3f3836a8ede68d7899224059ca1c1be8fbf3463452"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
