name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16b23c311d95877440c5be4f3633f251a049e9d086db20263f65fd19ca59d598"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
