name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.0.0.pre7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d6696617034654934aa7b23f0761de4752b04c5eedb1d8007e19e7fd1958726"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
