name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "780f39d27238574efe0c9205c6d7ec87b4a910ee95e3f1c7b93963cd289ec622"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
