name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adb115173f16320532e3536aaa4b89a78fc3e2c8c070958d47a7ad444374adac"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
