name = "InsomniaHardcore"
author = "CrismPack"
version = "2.0.0-pre1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b16947aa4c5b8a8683e345afaeec2c97e74e5d25b1fd9a9549a8df6c6f8a53"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
