name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfc71a0e2247c513f57e6a0fe7ff4ead81df5e9679f95a9cc8fee35291d87954"

[versions]
fabric = "0.14.18"
minecraft = "1.18.2"
