name = "InsomniaHardcore"
author = "CrismPack"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f747708dd9ff9566f84888f7272597ccc3b93d343d401ac5d740b1405450465"

[versions]
fabric = "0.14.19"
minecraft = "1.18.2"
