name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97e16f9e19b61297d04db241dcee709c4ba1e19f4677b1584cd234925e8e6dd8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
