name = "InsomniaHardcore-1.18.2"
author = "CrismPack"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e8929fed824fe02b8e351d14202f0b034c0dd37319098d7831adb03a1fd30d0"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"
