name = "InsomniaHardcore-1.20.1"
author = "CrismPack"
version = "2.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e951aebfe3a67ed4af93d09ac38aeaa145f424ebcfe583fe05621f7b275fba54"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
