name = "InsomniaHardcore"
author = "CrismPack"
version = "2.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3eac3a315473e381294139584b68d1295a37c35805b97a4c20c7efa487d93e1"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
