# Default configuration file for Fabric AntiXray mod by DrexHD

# Default values
enabled = false

# World specific values
[overworld]
enabled = true
engineMode = 2
maxBlockHeight = 256
updateRadius = 2
lavaObscures = false
hiddenBlocks = ["copper_ore", "deepslate_copper_ore", "raw_copper_block", "gold_ore", "deepslate_gold_ore", "raw_gold_block", "iron_ore", "deepslate_iron_ore", "raw_iron_block", "coal_ore", "deepslate_coal_ore", "lapis_ore", "deepslate_lapis_ore", "mossy_cobblestone", "obsidian", "chest", "diamond_ore", "deepslate_diamond_ore", "redstone_ore", "deepslate_redstone_ore", "clay", "emerald_ore", "deepslate_emerald_ore", "ender_chest", "create:zinc_ore", "create:deepslate_zinc_ore", "denseores:dense_coal_ore", "denseores:dense_copper_ore", "denseores:dense_iron_ore", "denseores:dense_gold_ore", "denseores:dense_redstone_ore", "denseores:dense_lapis_ore", "denseores:dense_diamond_ore", "denseores:dense_emerald_ore", "denseores:dense_deepslate_coal_ore", "denseores:dense_deepslate_copper_ore", "denseores:dense_deepslate_iron_ore", "denseores:dense_deepslate_gold_ore", "denseores:dense_deepslate_redstone_ore", "denseores:dense_deepslate_lapis_ore", "denseores:dense_deepslate_diamond_ore", "denseores:dense_deepslate_emerald_ore", "charm:oak_chest", "charm:oak_chest", "charm:spruce_chest", "charm:birch_chest", "charm:jungle_chest", "charm:acacia_chest", "charm:dark_oak_chest", "charm:crimson_chest", "charm:warped_chest", "charm:azalea_chest", "charm:ebony_chest", "betterend:mossy_glowshroom_chest", "betterend:pythadendron_chest", "betterend:end_lotus_chest", "betterend:lacugrove_chest", "betterend:dragon_tree_chest", "betterend:tenanea_chest", "betterend:helix_tree_chest", "betterend:umbrella_tree_chest", "betterend:jellyshroom_chest", "betterend:lucernia_chest"]
replacementBlocks = ["stone", "deepslate"]

[the_nether]
enabled = true
engineMode = 1
maxBlockHeight = 256
updateRadius = 2
lavaObscures = true
hiddenBlocks = ["ancient_debris", "nether_quartz_ore", "nether_gold_ore"]
replacementBlocks = ["netherrack"]