# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = [
    "the_aether",
    "netty",
    "Netty",
    "[bclib]",
    "[ShulkerBoxTooltip]",
    "'forge:entity_gravity'",
    "Parsing error loading recipe",
    "Couldn't parse loot table",
    "Failed to load model delightfulcreators:", "Failed to modify baked model after bake"
    ]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Failed to load model delightfulcreators:", "Failed to modify baked model after bake"]