
#General Config Section
[general]
	#The Application ID of the Discord App to use
	clientID = 864611964080095272
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 13
	updater = false

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "Insomnia: Hardcore is loading"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[init.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is currently lazy"
	#The seconds line of text under the app name
	state = "Chilling in the menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[main_menu.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a server"
	#The second line of text under the app name
	state = "Searching for friends"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[server_list.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is looking for a Realm"
	#The second line of text under the app name
	state = "Browsing Realms"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	
	#The buttons to display on Discord
	[[realms_list.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "%player% is joining a game"
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[join_game.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Currently In %world%"
	#The second line of text under the app name
	state = "Playing lonely mode"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[single_player.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %servername% with %players% players"
	#The second line of text under the app name
	state = "Playing online"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[multi_player.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on %realmname%"
	#The second line of text under the app name
	state = "Playing on a Realm"
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"
	
	#The buttons to display on Discord
	[[realms.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing Minecraft"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "insomnia"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Insomnia: Hardcore - Minecraft %mcver%"
	#The Asset ID of the image to display as the small image
	smallImageKey = "small"
	#The text that gets displayed when the small image is hovered
	smallImageText = "%mods% mods installed"

	#The buttons to display on Discord
	[[generic.buttons]]
		label = "Download Insomnia: Hardcore"
		url = "https://www.curseforge.com/minecraft/modpacks/insomnia-hardcore"

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

