name: Automatically publish to Modrinth and CurseForge

on:
  release:
    types: [published]

env:
  MC_VERSION: 1.20.1
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:   
  publish-to-curseforge:
    if: github.repository_owner == 'CrismPack'
    runs-on: ubuntu-24.04
    environment: github-actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download pack files
      uses: robinraju/release-downloader@v1.10
      id: download-files
      with:
        fileName: '*.zip'
        latest: true
        tarBall: false
        zipBall: false

    - name: Publish to CurseForge
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        name: "Insomnia v${{ steps.download-files.outputs.tag_name }} for ${{ env.MC_VERSION }}"
        changelog-file: CurseForge-Release.md

        curseforge-id: 560596
        curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
        # curseforge-files: |
        #   '!*@(-ServerPack-)*.zip'
        #   '*@(-ServerPack-)*.zip'
        
        files: | 
          '!(*-@(ServerPack)-*).zip'
          '*-@(ServerPack)-*.zip'

        loaders: fabric
        game-versions: ${{ env.MC_VERSION }}


  # publish-to-modrinth:
  #   if: github.repository_owner == 'CrismPack'
  #   runs-on: ubuntu-24.04
  #   environment: github-actions

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v3

  #   - name: Download pack files
  #     uses: robinraju/release-downloader@v1.10
  #     id: download-files
  #     with:
  #       fileName: '*.mrpack'
  #       latest: true
  #       tarBall: false
  #       zipBall: false

  #   - name: Publish to Modrinth
  #     uses: Kir-Antipov/mc-publish@v3.3
  #     with:
  #       name: Breakneck v${{ steps.download-files.outputs.tag_name }} for ${{ vars.MC_VERSION }}
  #       changelog-file: Modrinth-Release.md

  #       modrinth-id: qPrWu8wn
  #       modrinth-token: "${{env.MODRINTH_TOKEN}}"
  #       modrinth-files: '*.mrpack'

  #       loaders: fabric
  #       game-versions: ${{ vars.MC_VERSION }}